# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image_description',
            field=models.TextField(default='post image'),
        ),
    ]
